Migrated rest of the env. to fully build inside the container

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -37,9 +37,6 @@ definitions:
     sed -i='' -e "s|<SERVER_NAME>|${SERVER_NAME_WEB}|" proxy/conf.d/default.conf &&
     docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${PROXY_REPOSITORY}:${VERSION} --platform linux/amd64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${PROXY_REPOSITORY}:${VERSION} -f proxy/Dockerfile ./proxy &&
     docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${PROXY_REPOSITORY}:${VERSION}
-  container_build: &container_build
-    docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} --platform linux/amd64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} -f Dockerfile . &&
-    docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION}
 
 pipelines:
   custom:
@@ -55,32 +52,34 @@ pipelines:
                   - 'self.hosted'
                   - 'linux'
                   - 'web'
-                caches:
-                  - node
-                  - nextcache
-                  # - docker
                 script:
                   # Install required tools
                   - *install_tools
                   # Install AWS CLI
                   - *install_aws_cli
-                  # Upgrade to latest stable version of npm
-                  - *upgrade_npm
-                  - *print_versions
-                  # Install dependencies
-                  - npm install --no-audit
-                  # Run tests
-                  # - npm run test
                   # RPC config
                   - cp -p ./src/Assets/networks/rpc_config_testnet.json ./src/Assets/networks/rpc_config.json
-                  # Build frontend
-                  - *app_build
                   # Login to ECR
                   - *aws_ecr_login
                   # Copy RPC config to Admin S3 Bucket
                   - aws s3 cp ./src/Assets/networks/rpc_config_testnet.json s3://test-ebisusbay-admin-storage/rpc_config.json
-                  # Build current/latest container image
-                  - *container_build
+                  # Build application container
+                  - |
+                      set +e # turn off error-trapping
+
+                      docker build --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV} --build-arg NEXT_PUBLIC_SITE24X7_KEY=${NEXT_PUBLIC_SITE24X7_KEY} --build-arg NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN} --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} --platform linux/amd64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} -f Dockerfile .
+                      RETURN_CODE=$?
+
+                      if [ $RETURN_CODE -eq 0 ]; then
+                        echo ""************BUILD OK, pushing container image..."************"
+                        docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION}
+                      else
+                        echo "************BUILD FAILED************"
+                        exit 1
+                      fi
+
+                      set -e # turn on error-trapping
+                  # Build proxy container
                   - *proxy_container_build
                   # deploy test-ebisusbay-web-amd64-us-east-1 / testapp.ebisusbay.biz
                   - 'curl -X POST -is -H "Authorization: Basic ${BITBUCKET_API_KEY}" -H "Content-Type: application/json" -d "{\"target\":{\"ref_type\":\"branch\",\"type\":\"pipeline_ref_target\",\"ref_name\":\"testnet\"}}" https://api.bitbucket.org/2.0/repositories/ebisusbay/eb_web_deploy/pipelines/'
@@ -96,32 +95,34 @@ pipelines:
                   - 'self.hosted'
                   - 'linux'
                   - 'web'
-                caches:
-                  - node
-                  - nextcache
-                  # - docker
                 script:
                   # Install required tools
                   - *install_tools
                   # Install AWS CLI
                   - *install_aws_cli
-                  # Upgrade to latest stable version of npm
-                  - *upgrade_npm
-                  - *print_versions
-                  # Install dependencies
-                  - npm install --no-audit
-                  # Run tests
-                  # - npm run test
                   # RPC config
                   - cp -p ./src/Assets/networks/rpc_config_dev.json ./src/Assets/networks/rpc_config.json
-                  # Build frontend
-                  - *app_build
                   # Login to ECR
                   - *aws_ecr_login
                   # Copy RPC config to Admin S3 Bucket
                   - aws s3 cp ./src/Assets/networks/rpc_config_dev.json s3://dev-ebisusbay-admin-storage/rpc_config.json
-                  # Build current/latest container image
-                  - *container_build
+                  # Build application container
+                  - |
+                      set +e # turn off error-trapping
+
+                      docker build --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV} --build-arg NEXT_PUBLIC_SITE24X7_KEY=${NEXT_PUBLIC_SITE24X7_KEY} --build-arg NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN} --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} --platform linux/amd64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} -f Dockerfile .
+                      RETURN_CODE=$?
+
+                      if [ $RETURN_CODE -eq 0 ]; then
+                        echo ""************BUILD OK, pushing container image..."************"
+                        docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION}
+                      else
+                        echo "************BUILD FAILED************"
+                        exit 1
+                      fi
+
+                      set -e # turn on error-trapping
+                  # Build proxy container
                   - *proxy_container_build
                   # deploy sandbox-ebisusbay-web-amd64-us-east-1 / sandboxapp.ebisusbay.biz
                   - 'curl -X POST -is -H "Authorization: Basic ${BITBUCKET_API_KEY}" -H "Content-Type: application/json" -d "{\"target\":{\"ref_type\":\"branch\",\"type\":\"pipeline_ref_target\",\"ref_name\":\"sandbox\"}}" https://api.bitbucket.org/2.0/repositories/ebisusbay/eb_web_deploy/pipelines/'
@@ -137,32 +138,34 @@ pipelines:
                   - 'self.hosted'
                   - 'linux'
                   - 'web'
-                caches:
-                  - node
-                  - nextcache
-                  # - docker
                 script:
                   # Install required tools
                   - *install_tools
                   # Install AWS CLI
                   - *install_aws_cli
-                  # Upgrade to latest stable version of npm
-                  - *upgrade_npm
-                  - *print_versions
-                  # Install dependencies
-                  - npm install --no-audit
-                  # Run tests
-                  # - npm run test
                   # RPC config
                   # - cp -p ./src/Assets/networks/rpc_config_dev.json ./src/Assets/networks/rpc_config.json
-                  # Build frontend
-                  - *app_build
                   # Login to ECR
                   - *aws_ecr_login
                   # Copy RPC config to Admin S3 Bucket
                   - aws s3 cp ./src/Assets/networks/rpc_config.json s3://prod-ebisusbay-admin-storage/rpc_config.json
-                  # Build current/latest container image
-                  - *container_build
+                  # Build application container
+                  - |
+                      set +e # turn off error-trapping
+
+                      docker build --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV} --build-arg NEXT_PUBLIC_SITE24X7_KEY=${NEXT_PUBLIC_SITE24X7_KEY} --build-arg NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN} --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} --platform linux/amd64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} -f Dockerfile .
+                      RETURN_CODE=$?
+
+                      if [ $RETURN_CODE -eq 0 ]; then
+                        echo ""************BUILD OK, pushing container image..."************"
+                        docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION}
+                      else
+                        echo "************BUILD FAILED************"
+                        exit 1
+                      fi
+
+                      set -e # turn on error-trapping
+                  # Build proxy container
                   - *proxy_container_build
                   # deploy prod-ebisusbay-web-amd64-us-east-1 / app.ebisusbay.com
                   - 'curl -X POST -is -H "Authorization: Basic ${BITBUCKET_API_KEY}" -H "Content-Type: application/json" -d "{\"target\":{\"type\":\"pipeline_ref_target\",\"ref_type\":\"branch\",\"ref_name\":\"prod\",\"selector\":{\"type\":\"custom\",\"pattern\":\"fast_hotfix_deployment_prod\"}}}" https://api.bitbucket.org/2.0/repositories/ebisusbay/eb_web_deploy/pipelines/'
@@ -194,7 +197,7 @@ pipelines:
                   - |
                       set +e # turn off error-trapping
 
-                      docker build --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV} --build-arg NEXT_PUBLIC_SITE24X7_KEY=${NEXT_PUBLIC_SITE24X7_KEY} --build-arg NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN} --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} --platform linux/amd64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} -f Dockerfile_testing .
+                      docker build --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV} --build-arg NEXT_PUBLIC_SITE24X7_KEY=${NEXT_PUBLIC_SITE24X7_KEY} --build-arg NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN} --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} --platform linux/amd64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} -f Dockerfile .
                       RETURN_CODE=$?
 
                       if [ $RETURN_CODE -eq 0 ]; then
@@ -222,32 +225,34 @@ pipelines:
                   - 'self.hosted'
                   - 'linux'
                   - 'web'
-                caches:
-                  - node
-                  - nextcache
-                  # - docker
                 script:
                   # Install required tools
                   - *install_tools
                   # Install AWS CLI
                   - *install_aws_cli
-                  # Upgrade to latest stable version of npm
-                  - *upgrade_npm
-                  - *print_versions
-                  # Install dependencies
-                  - npm install --no-audit
-                  # Run tests
-                  # - npm run test
                   # RPC config
                   # - cp -p ./src/Assets/networks/rpc_config_dev.json ./src/Assets/networks/rpc_config.json
-                  # Build frontend
-                  - *app_build
                   # Login to ECR
                   - *aws_ecr_login
                   # Copy RPC config to Admin S3 Bucket
                   - aws s3 cp ./src/Assets/networks/rpc_config.json s3://prod-ebisusbay-admin-storage/rpc_config.json
-                  # Build current/latest container image
-                  - *container_build
+                  # Build application container
+                  - |
+                      set +e # turn off error-trapping
+
+                      docker build --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV} --build-arg NEXT_PUBLIC_SITE24X7_KEY=${NEXT_PUBLIC_SITE24X7_KEY} --build-arg NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN} --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} --platform linux/amd64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} -f Dockerfile .
+                      RETURN_CODE=$?
+
+                      if [ $RETURN_CODE -eq 0 ]; then
+                        echo ""************BUILD OK, pushing container image..."************"
+                        docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION}
+                      else
+                        echo "************BUILD FAILED************"
+                        exit 1
+                      fi
+
+                      set -e # turn on error-trapping
+                  # Build proxy container
                   - *proxy_container_build
                   # deploy prod-ebisusbay-web-amd64-us-east-1 / app.ebisusbay.com
                   - 'curl -X POST -is -H "Authorization: Basic ${BITBUCKET_API_KEY}" -H "Content-Type: application/json" -d "{\"target\":{\"ref_type\":\"branch\",\"type\":\"pipeline_ref_target\",\"ref_name\":\"prod\"}}" https://api.bitbucket.org/2.0/repositories/ebisusbay/eb_web_deploy/pipelines/'
