More caching during container build & whole build happens now inside the container itself

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -8,7 +8,7 @@ definitions:
   services:
     docker:
       # default memory is 1024MB
-      memory: 3072
+      memory: 7168
       image: public.ecr.aws/docker/library/docker:dind
   caches:
     nextcache: .next/cache
@@ -36,26 +36,12 @@ definitions:
     sed -i='' -e "s|<SERVER_NAME>|${SERVER_NAME_WEB}|" proxy/conf.d/default.conf &&
     docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${PROXY_REPOSITORY}:${VERSION} --platform linux/amd64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${PROXY_REPOSITORY}:${VERSION} -f proxy/Dockerfile ./proxy &&
     docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${PROXY_REPOSITORY}:${VERSION}
+    # --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${PROXY_REPOSITORY}:${VERSION}-build-${BITBUCKET_BUILD_NUMBER}
   container_build: &container_build
     docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} --platform linux/amd64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} -f Dockerfile . &&
     docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION}
+    # --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${PROXY_REPOSITORY}:${VERSION}-build-${BITBUCKET_BUILD_NUMBER}
 
-  # Docker Buildx version
-  docker_buildx: &docker_buildx
-    docker --version &&
-    docker pull docker/buildx-bin:latest &&
-    docker container create --name buildx docker/buildx-bin:latest docker buildx version &&
-    mkdir -p /usr/libexec/docker/cli-plugins/ &&
-    docker container cp buildx:/buildx /usr/libexec/docker/cli-plugins/docker-buildx &&
-    docker run --rm --privileged multiarch/qemu-user-static --reset -p yes &&
-    docker buildx create --use &&
-    docker buildx version
-  proxy_container_buildx: &proxy_container_buildx
-    sed -i='' -e "s|<SERVER_NAME>|${SERVER_NAME_WEB}|" proxy/conf.d/web.conf &&
-    sed -i='' -e "s|<SERVER_NAME>|${SERVER_NAME_WEB}|" proxy/conf.d/default.conf &&
-    docker buildx build --push --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${PROXY_REPOSITORY}:${VERSION} --platform linux/amd64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${PROXY_REPOSITORY}:${VERSION} --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${PROXY_REPOSITORY}:${VERSION}-build-${BITBUCKET_BUILD_NUMBER} -f proxy/Dockerfile ./proxy
-  container_buildx: &container_buildx
-    docker buildx build --push --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${PROXY_REPOSITORY}:${VERSION} --platform linux/amd64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION}-build-${BITBUCKET_BUILD_NUMBER} -f Dockerfile .
 pipelines:
   custom:
     deploy-to-testnet:
@@ -83,7 +69,7 @@ pipelines:
                   - *upgrade_npm
                   - *print_versions
                   # Install dependencies
-                  - npm ci --no-audit
+                  - npm install --no-audit
                   # Run tests
                   # - npm run test
                   # RPC config
@@ -124,7 +110,7 @@ pipelines:
                   - *upgrade_npm
                   - *print_versions
                   # Install dependencies
-                  - npm ci --no-audit
+                  - npm install --no-audit
                   # Run tests
                   # - npm run test
                   # RPC config
@@ -140,9 +126,9 @@ pipelines:
                   - *proxy_container_build
                   # deploy sandbox-ebisusbay-web-amd64-us-east-1 / sandboxapp.ebisusbay.biz
                   - 'curl -X POST -is -H "Authorization: Basic ${BITBUCKET_API_KEY}" -H "Content-Type: application/json" -d "{\"target\":{\"ref_type\":\"branch\",\"type\":\"pipeline_ref_target\",\"ref_name\":\"sandbox\"}}" https://api.bitbucket.org/2.0/repositories/ebisusbay/eb_web_deploy/pipelines/'
-    buildx-testing:
+    build-testing:
       - stage:
-          name: buildx-testing
+          name: build-testing
           deployment: Sandbox
           steps:
             - step:
@@ -152,35 +138,37 @@ pipelines:
                   - 'self.hosted'
                   - 'linux'
                   - 'web'
-                caches:
-                  - node
-                  - nextcache
-                  # - docker
                 script:
                   # Install required tools
                   - *install_tools
                   # Install AWS CLI
                   - *install_aws_cli
-                  # Upgrade to latest stable version of npm
-                  - *upgrade_npm
-                  - *print_versions
-                  # Install dependencies
-                  - npm ci --no-audit
-                  # Run tests
-                  # - npm run test
                   # RPC config
                   # - cp -p ./src/Assets/networks/rpc_config_dev.json ./src/Assets/networks/rpc_config.json
-                  # Build frontend
-                  - *app_build
-                  # Install and configure Docker Buildx
-                  - *docker_buildx
                   # Login to ECR
                   - *aws_ecr_login
                   # Copy RPC config to Admin S3 Bucket
                   # - aws s3 cp ./src/Assets/networks/rpc_config_dev.json s3://dev-ebisusbay-admin-storage/rpc_config.json
-                  # Build current/latest container image
-                  - *container_buildx
-                  - *proxy_container_buildx
+                  # Build application container
+                  - |
+                      set +e # turn off error-trapping
+
+                      docker build --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV} --build-arg NEXT_PUBLIC_SITE24X7_KEY=${NEXT_PUBLIC_SITE24X7_KEY} --build-arg NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN} --cache-from ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} --platform linux/amd64 --tag ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION} -f Dockerfile_testing .
+                      RETURN_CODE=$?
+
+                      if [ $RETURN_CODE -eq 0 ]; then
+                        echo ""************BUILD OK, pushing container image..."************"
+                        docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${APP_REPOSITORY}:${VERSION}
+                      else
+                        echo "************BUILD FAILED************"
+                        exit 1
+                      fi
+
+                      set -e # turn on error-trapping
+                  # Build proxy container
+                  - *proxy_container_build
+                  # deploy sandbox-ebisusbay-web-amd64-us-east-1 / sandboxapp.ebisusbay.biz
+                  # - 'curl -X POST -is -H "Authorization: Basic ${BITBUCKET_API_KEY}" -H "Content-Type: application/json" -d "{\"target\":{\"ref_type\":\"branch\",\"type\":\"pipeline_ref_target\",\"ref_name\":\"sandbox\"}}" https://api.bitbucket.org/2.0/repositories/ebisusbay/eb_web_deploy/pipelines/'
     when-shit-hits-the-fan-prod:
       - stage:
           name: app.ebisusbay.com
@@ -206,7 +194,7 @@ pipelines:
                   - *upgrade_npm
                   - *print_versions
                   # Install dependencies
-                  - npm ci --no-audit
+                  - npm install --no-audit
                   # Run tests
                   # - npm run test
                   # RPC config
@@ -248,7 +236,7 @@ pipelines:
                   - *upgrade_npm
                   - *print_versions
                   # Install dependencies
-                  - npm ci --no-audit
+                  - npm install --no-audit
                   # Run tests
                   # - npm run test
                   # RPC config
@@ -289,7 +277,7 @@ pipelines:
                   - *upgrade_npm
                   - *print_versions
                   # Install dependencies
-                  - npm ci --no-audit
+                  - npm install --no-audit
                   # Run tests
                   # - npm run test
                   # RPC config
